---
version: 0.2.27
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: K8S
mount_path: ./
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  infrastructure_ip: 10.0.0.100
  # Worker IPs are simply incremented from the control IP.
  control_ip: 10.0.0.101
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  infrastructure:
    cpu: 2
    memory: 4144
  control:
    cpu: 2
    memory: 4144
  workers:
    count: 2
    cpu: 2
    memory: 4144
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
# shared_folders:
#   - host_path: ../images
#     vm_path: /vagrant/images
software:
  box: bento/ubuntu-22.04
  # To skip the dashboard installation, set its version to an empty value or comment it out:
  # dashboard: 2.7.0
  os: xUbuntu_22.04
  kubernetes: v1.29
  crio: 1.28

provider: virtualbox